import { StyleSheet } from "react-native";

const createHomeStyles = (colors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    searchContainer: {
      backgroundColor: colors.card,
      borderBottomColor: "transparent",
      borderTopColor: "transparent",
      color: colors.text,
    },
    searchInputContainer: {
      backgroundColor: colors.border,
      borderBottomColor: colors.border,
    },
    map: {
      flex: 1,
    },
    filterButton: {
      backgroundColor: colors.card,
      padding: 5,
      borderRadius: 5,
      alignItems: "center",
      borderWidth: 1,
      borderColor: colors.text,
      width: 40,
      height: 35,
    },
    historyButton: {
      backgroundColor: colors.card,
      padding: 5,
      borderRadius: 5,
      alignItems: "center",
      borderWidth: 1,
      borderColor: colors.text,
      width: 40,
      height: 35,
    },
    customPinButton: {
      backgroundColor: colors.card,
      padding: 5,
      borderRadius: 5,
      alignItems: "center",
      borderWidth: 1,
      borderColor: colors.text,
      width: 40,
      height: 35,
      flexDirection: "row",
      justifyContent: "center",
    },
    buttonText: {
      color: colors.garnetWhite,
      fontSize: 16,
      fontWeight: "bold",
    },
    pinActionsContainer: {
      flexDirection: "row",
      justifyContent: "space-around",
      marginTop: 10,
    },
    pinActionButton: {
      backgroundColor: colors.card,
      padding: 5,
      marginBottom: 5,
      borderRadius: 5,
      alignItems: "center",
      borderWidth: 1,
      borderColor: colors.text,
    },
    pinActionText: {
      color: colors.text,
      fontSize: 16,
      fontWeight: "bold",
    },
    modalContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "rgba(0,0,0,0.5)",
    },
    modalView: {
      width: 300,
      backgroundColor: colors.card,
      borderRadius: 10,
      padding: 20,
      alignItems: "center",
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 4,
      elevation: 5,
    },
    modalText: {
      marginBottom: 15,
      textAlign: "center",
      fontSize: 18,
      color: colors.text,
    },
    modalInput: {
      width: "100%",
      borderBottomWidth: 1,
      borderColor: colors.text,
      marginBottom: 15,
      padding: 5,
      fontSize: 16,
      color: colors.text,
    },
    trafficButton: {
      backgroundColor: colors.card,
      padding: 5,
      borderRadius: 5,
      alignItems: "center",
      borderWidth: 1,
      borderColor: colors.text,
      width: 40,
      height: 35,
    },
    travelModeOverlay: {
      position: "absolute",
      top: 130,
      left: 12,
      backgroundColor: colors.card,
      borderRadius: 5,
      padding: 5,
      elevation: 5,
    },
    travelModeButton: {
      padding: 3,
      borderRadius: 5,
      backgroundColor: colors.card,
      marginVertical: 5,
    },
    activeTravelMode: {
      backgroundColor: "#aaaaaa",
    },
    travelModeText: {
      color: colors.text,
    },
    routeDetailsContainer: {
      position: "absolute",
      bottom: 50,
      left: 20,
      right: 20,
      backgroundColor: colors.card,
      padding: 10,
      borderRadius: 5,
      elevation: 5,
      opacity: 0.9,
    },
    routeDetailsText: {
      fontSize: 15,
      marginBottom: 5,
      color: colors.text,
    },
    routeButton: {
      backgroundColor: colors.card,
      paddingLeft: 10,
      paddingRight: 10,
      paddingTop: 5,
      paddingBottom: 5,
      marginLeft: 0,
      marginRight: 0,
      borderColor: colors.garnetWhite,
      borderWidth: 1,
      borderRadius: 5,
      alignItems: "center",
      justifyContent: "center",
    },
    routeButtonText: {
      color: colors.text,
      fontSize: 16,
    },
    buttonContainer: {
      flexDirection: "row",
      justifyContent: "space-center",
      alignItems: "center",
      gap: 10,
      paddingHorizontal: 5,
      marginVertical: 10,
    },
    routeButtonsContainer: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      gap: 10,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
    },
    exitButton: {
      backgroundColor: colors.card,
      padding: 5,
      borderRadius: 5,
      alignItems: "center",
      borderWidth: 1,
      borderColor: colors.text,
      width: 40,
      height: 35,
      justifyContent: "flex-end",
      margin: 5,
    },
    titleContainer: {
      flexDirection: "row",
      justifyContent: "space-between",
    },
    exitButtonContainer: {
      flexDirection: "row",
      justifyContent: "flex-end",
    },
    highlightedButton: {
      backgroundColor: "#FBD690",
      borderColor: colors.primary,
      borderWidth: 2,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.8,
      shadowRadius: 4,
      elevation: 5,
    },
    tutorialOverlay: {
      flex: 1,
      justifyContent: "flex-start",
      alignItems: "center",
      paddingTop: 80,
      borderRadius: 20,
      borderColor: colors.text,
    },
    tutorialContent: {
      backgroundColor: colors.card,
      padding: 12,
      borderRadius: 20,
      borderColor: colors.text,
      alignItems: "center",
      marginTop: 50,
    },
    tutorialTitle: {
      fontSize: 18,
      fontWeight: "bold",
      marginBottom: 10,
      color: colors.text,
    },
    tutorialDescription: {
      fontSize: 16,
      marginBottom: 20,
      color: colors.text,
    },
    tutorialButtons: {
      flexDirection: "row",
      justifyContent: "space-between",
    },
    tutorialButton: {
      marginHorizontal: 10,
      padding: 10,
      backgroundColor: colors.card,
      borderRadius: 5,
    },
    tutorialButtonText: {
      color: colors.text,
    },
    tutorialStepIndicator: {
      position: "absolute",
      top: 10,
      right: 10,
      backgroundColor: "rgba(255, 255, 255, 0.8)",
      padding: 5,
      borderRadius: 5,
    },
    tutorialStepText: {
      fontSize: 14,
      color: colors.primary,
    },
  });

export default createHomeStyles;
