import { StyleSheet } from "react-native";

const createHomeStyles = (colors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    searchContainer: {
      backgroundColor: colors.card,
      borderRadius: 25,
      borderBottomColor: "transparent",
      borderTopColor: "transparent",
      color: colors.text,
      marginHorizontal: 8,
      marginVertical: 8,
      paddingHorizontal: 8,
      height: 40,
    },
    textInput: {
      height: 40,
      paddingVertical: 0,
      textAlignVertical: "center",
      fontSize: 16,
      lineHeight: 20,
      color: colors.garnetWhite,
    },
    map: {
      flex: 1,
    },
    filterButton: {
      backgroundColor: colors.card,
      padding: 5,
      borderRadius: 5,
      alignItems: "center",
      borderWidth: 1,
      borderColor: colors.text,
      width: 40,
      height: 35,
    },
    historyButton: {
      backgroundColor: colors.card,
      padding: 5,
      borderRadius: 5,
      alignItems: "center",
      borderWidth: 1,
      borderColor: colors.text,
      width: 40,
      height: 35,
    },
    customPinButton: {
      backgroundColor: colors.card,
      padding: 5,
      borderRadius: 5,
      alignItems: "center",
      borderWidth: 1,
      borderColor: colors.text,
      width: 40,
      height: 35,
      flexDirection: "row",
      justifyContent: "center",
    },
    buttonText: {
      color: colors.garnetWhite,
      fontSize: 16,
      fontWeight: "bold",
    },
    pinActionsContainer: {
      flexDirection: "row",
      justifyContent: "space-around",
      marginTop: 10,
    },
    pinActionButton: {
      backgroundColor: colors.card,
      padding: 5,
      marginBottom: 5,
      borderRadius: 5,
      alignItems: "center",
      borderWidth: 1,
      borderColor: colors.text,
    },
    pinActionText: {
      color: colors.text,
      fontSize: 16,
      fontWeight: "bold",
    },
    // Adding custom pin popup          COME BACK TO HERE & CHANGE USING colors
    notificationBox: {
      position: "absolute",
      top: 20, // Distance from the top of the screen
      left: "10%", // Center the box horizontally
      right: "10%",
      backgroundColor: "#73000A",
      padding: 10,
      borderRadius: 10,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 4,
      elevation: 5, // For Android shadow
      zIndex: 1000, // Ensure it appears above other components
    },
    notificationText: {
      color: "white",
      fontSize: 16,
      fontWeight: "bold",
      textAlign: "center",
    },
    // cancelling creating custom pin
    cancelButton: {
      backgroundColor: "white",
      paddingVertical: 8,
      paddingHorizontal: 20,
      borderRadius: 5,
      marginTop: 8,
    },
    cancelButtonText: {
      color: "#73000A", // Garnet color for text
      fontSize: 14,
      fontWeight: "bold",
    },
    modalContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "rgba(0,0,0,0.5)",
    },
    modalView: {
      width: "80%",
      backgroundColor: colors.card,
      borderRadius: 10,
      padding: 20,
      alignItems: "center",
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 4,
      elevation: 5,
    },
    modalText: {
      marginBottom: 15,
      textAlign: "left",
      fontSize: 18,
      color: colors.text,
      maxWidth: "85%",
    },
    modalInput: {
      width: "100%",
      borderBottomWidth: 1,
      borderColor: colors.text,
      marginBottom: 15,
      padding: 5,
      fontSize: 16,
      color: colors.text,
    },
    modalButtonContainer: {
      flexDirection: "row",
      gap: 5,
      justifyContent: "space-between",
    },

    // specifically for info modal on map screen
    // info model in settings was still bright in dark mode, so made my own -Chloe
    modalTitleInfo: {
      fontSize: 18,
      fontFamily: "Abel_400Regular",
      marginBottom: 10,
      color: colors.text,
    },
    modalCloseText: {
      color: colors.text,
      textAlign: "right",
      fontSize: 16,
    },

    // For the Info Button on the map screen
    infoButton: {
      position: "absolute", // Allows precise positioning
      bottom: 10, // increase to put it further up
      right: 10,
      padding: 5,
      borderRadius: 20,
      width: 40,
      height: 40,
      alignItems: "center",
      justifyContent: "center",
    },
    plusText: {
      fontSize: 14,
      fontWeight: "bold",
      color: colors.text,
      marginLeft: 2,
    },

    trafficButton: {
      backgroundColor: colors.card,
      padding: 5,
      borderRadius: 5,
      alignItems: "center",
      borderWidth: 1,
      borderColor: colors.text,
      width: 40,
      height: 35,
    },
    travelModeOverlay: {
      position: "absolute",
      top: 130,
      left: 12,
      backgroundColor: colors.card,
      borderRadius: 5,
      padding: 5,
      elevation: 5,
    },
    travelModeButton: {
      padding: 3,
      borderRadius: 5,
      backgroundColor: colors.card,
      marginVertical: 5,
    },
    activeTravelMode: {
      backgroundColor: "#aaaaaa",
    },
    travelModeText: {
      color: colors.text,
    },
    routeDetailsContainer: {
      position: "absolute",
      bottom: 50,
      left: 10,
      right: 10,
      backgroundColor: colors.card,
      padding: 15,
      borderRadius: 5,
      elevation: 5,
      opacity: 0.9,
      flexDirection: "column",
    },
    routeDetailsText: {
      fontSize: 15,
      marginBottom: 5,
      color: colors.text,
      flexShrink: 1,
    },
    routeButton: {
      backgroundColor: colors.card,
      paddingLeft: 10,
      paddingRight: 10,
      paddingTop: 5,
      paddingBottom: 5,
      marginLeft: 0,
      marginRight: 0,
      borderColor: colors.garnetWhite,
      borderWidth: 1,
      borderRadius: 5,
      alignItems: "center",
      justifyContent: "center",
    },
    routeButtonText: {
      color: colors.text,
      fontSize: 16,
    },
    buttonContainer: {
      flexDirection: "row",
      justifyContent: "space-center",
      alignItems: "center",
      gap: 10,
      paddingHorizontal: 5,
      marginVertical: 10,
    },
    routeButtonsContainer: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      width: "100%",
    },
    loadingContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
    },
    titleContainer: {
      flexDirection: "row",
      justifyContent: "space-between",
      position: "relative",
      alignItems: "flex-start",
      minHeight: 60,
      flexWrap: "wrap",
      paddingRight: 50,
      marginBottom: 10,
    },
    titleText: {
      fontSize: 15,
      color: colors.text,
      flex: 1,
      paddingRight: 50,
      minHeight: 60,
      flexShrink: 1,
    },
    exitButtonContainer: {
      flexDirection: "row",
      justifyContent: "flex-end",
      position: "absolute",
      right: 0,
      top: 0,
      width: 90,
      paddingLeft: 5,
    },
    exitButton: {
      backgroundColor: colors.card,
      padding: 5,
      borderRadius: 5,
      alignItems: "center",
      borderWidth: 1,
      borderColor: colors.text,
      width: 40,
      height: 35,
      margin: 5,
    },
    highlightedButton: {
      backgroundColor: "#FBD690",
      borderColor: colors.primary,
      borderWidth: 2,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.8,
      shadowRadius: 4,
      elevation: 5,
    },
    tutorialOverlay: {
      flex: 1,
      justifyContent: "flex-start",
      alignItems: "center",
      paddingTop: 80,
      borderRadius: 20,
      borderColor: colors.text,
    },
    tutorialOverlayTop: {
      flex: 1,
      justifyContent: "flex-start",
      alignItems: "center",
      paddingTop: 80,
      borderRadius: 20,
      borderColor: colors.text,
    },
    tutorialOverlayBottom: {
      flex: 1,
      justifyContent: "flex-end",
      alignItems: "center",
      paddingBottom: 80,
      borderRadius: 20,
      borderColor: colors.text,
    },
    tutorialContent: {
      backgroundColor: colors.card,
      padding: 12,
      borderRadius: 20,
      borderColor: colors.text,
      alignItems: "center",
      marginTop: 50,
    },
    tutorialTitle: {
      fontSize: 18,
      fontWeight: "bold",
      marginBottom: 10,
      color: colors.text,
    },
    tutorialDescription: {
      fontSize: 16,
      marginBottom: 20,
      color: colors.text,
    },
    tutorialButtons: {
      flexDirection: "row",
      justifyContent: "space-between",
    },
    tutorialButton: {
      marginHorizontal: 10,
      padding: 10,
      backgroundColor: colors.card,
      borderRadius: 5,
    },
    tutorialButtonText: {
      color: colors.text,
    },
    tutorialStepIndicator: {
      backgroundColor: "rgba(255, 255, 255, 0.8)",
      padding: 5,
      borderRadius: 5,
      justifyContent: "center",
      alignItems: "center",
    },
    tutorialFlex: {
      justifyContent: "space-between",
      alignItems: "center",
      flexDirection: "row",
      width: "100%",
    },
    tutorialStepText: {
      fontSize: 14,
      color: colors.primary,
    },
  });

export default createHomeStyles;
