import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  searchContainer: {
    backgroundColor: "white",
    borderBottomColor: "transparent",
    borderTopColor: "transparent",
  },
  searchInputContainer: {
    backgroundColor: "#EDEDED",
  },
  map: {
    flex: 1,
  },
  filterButton: {
    backgroundColor: "#e2e2e2",
    padding: 5,
    borderRadius: 5,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "black",
    width: 40,
    height: 35,
  },
  historyButton: {
    backgroundColor: "#e2e2e2",
    padding: 5,
    borderRadius: 5,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "black",
    width: 40,
    height: 35,
  },
  // Start of code for custom pins
  customPinButton: {
    backgroundColor: "#e2e2e2",
    padding: 5,
    borderRadius: 5,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "black",
    width: 40,
    height: 35,
    flexDirection: "row",
    justifyContent: "center",
  },
  buttonText: {
    color: "#73000A",
    fontSize: 16,
    fontWeight: "bold",
  },
  pinActionsContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginTop: 10,
  },
  pinActionButton: {
    backgroundColor: "#e2e2e2",
    padding: 5,
    marginBottom: 5,
    borderRadius: 5,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "black",
  },
  pinActionText: {
    color: "#73000A",
    fontSize: 16,
    fontWeight: "bold",
  },
  // renaming pin
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  modalView: {
    width: 300,
    backgroundColor: "white",
    borderRadius: 10,
    padding: 20,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalText: {
    marginBottom: 15,
    textAlign: "center",
    fontSize: 18,
  },
  modalInput: {
    width: "100%",
    borderBottomWidth: 1,
    marginBottom: 15,
    padding: 5,
    fontSize: 16,
  },

  // End of code for custom pins
  trafficButton: {
    backgroundColor: "#e2e2e2",
    padding: 5,
    borderRadius: 5,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "black",
    width: 40,
    height: 35,
  },
  travelModeOverlay: {
    position: "absolute",
    top: 130,
    left: 12,
    backgroundColor: "white",
    borderRadius: 5,
    padding: 5,
    elevation: 5,
  },
  travelModeButton: {
    padding: 3,
    borderRadius: 5,
    backgroundColor: "#e2e2e2",
    marginVertical: 5,
  },
  activeTravelMode: {
    backgroundColor: "#aaaaaa",
  },
  travelModeText: {
    color: "black",
  },
  routeDetailsContainer: {
    position: "absolute",
    bottom: 50,
    left: 20,
    right: 20,
    backgroundColor: "white",
    padding: 10,
    borderRadius: 5,
    elevation: 5,
    opacity: 0.9,
  },
  routeDetailsText: {
    fontSize: 15,
    marginBottom: 5,
  },
  routeButton: {
    backgroundColor: "#e2e2e2",
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 5,
    paddingBottom: 5,
    marginLeft: 0,
    marginRight: 0,
    borderRadius: 5,
    alignItems: "center",
    justifyContent: "center",
  },
  routeButtonText: {
    color: "black",
    fontSize: 16,
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "space-center",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 5,
    marginVertical: 10,
  },
  routeButtonsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  exitButton: {
    backgroundColor: "#e2e2e2",
    padding: 5,
    borderRadius: 5,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "black",
    width: 40,
    height: 35,
    justifyContent: "flex-end",
  },
  titleContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
});
